import { School, User, Subject, Student, Score, PredictionScore, ActualCutoff, AuditLog, ExcelColumnMapping, PastCutoffRecord } from '../types';

export const initialSchool: School = {
  id: 'sch_1',
  name: '전주대학교사범대학부설고등학교',
  code: 'JJBUGO_HS_2026',
};

export const initialUsers: User[] = [
  {
    id: 'usr_admin',
    name: '성적관리부 관리자',
    email: 'admin@jjbugo.hs.kr',
    password: 'admin',
    role: 'ADMIN',
    schoolId: 'sch_1',
    assignedSubjectIds: ['sub_math'],
    approved: true,
    createdAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'usr_teacher_math1',
    name: '김수학 교사',
    email: 'teacher@jjbugo.hs.kr',
    password: 'teacher',
    role: 'TEACHER',
    schoolId: 'sch_1',
    assignedSubjectIds: ['sub_math'],
    approved: true,
    createdAt: '2026-08-01T00:00:00.000Z',
  },
];

export const initialSubjects: Subject[] = [
  {
    id: 'sub_math',
    schoolId: 'sch_1',
    name: '수학 I',
    grade: 1,
    semester: 1,
    midtermWeight: 30,
    performanceWeight: 30,
    finalWeight: 40,
    midtermMaxScore: 100,
    performanceMaxScore: 40,
    finalMaxScore: 100,
  },
];

// Clean slate: No mock students or mock scores
export const initialStudents: Student[] = [];
export const initialScores: Score[] = [];
export const initialPredictions: PredictionScore[] = [];
export const initialActualCutoffs: ActualCutoff[] = [];
export const initialAuditLogs: AuditLog[] = [];

export const initialPastCutoffs: PastCutoffRecord[] = [
  {
    id: 'past_2025_1_math1',
    schoolYear: 2025,
    semester: 1,
    grade: 1,
    subjectName: '수학 I',
    midtermWeight: 30,
    performanceWeight: 30,
    finalWeight: 40,
    cutoffA: 87.2,
    cutoffB: 74.6,
    cutoffC: 61.8,
    cutoffD: 49.5,
    studentCount: 195,
    meanScore: 63.4,
    stdDev: 19.8,
    sourceType: 'CURRENT_ARCHIVE',
    notes: '2025학년도 1학기 최종 확정 분할점수 (기말고사 변별력 보통)',
    createdBy: '김수학 교사',
    createdAt: '2025-07-20T10:00:00.000Z',
  },
  {
    id: 'past_2025_2_math1',
    schoolYear: 2025,
    semester: 2,
    grade: 1,
    subjectName: '수학 I',
    midtermWeight: 30,
    performanceWeight: 30,
    finalWeight: 40,
    cutoffA: 86.0,
    cutoffB: 73.8,
    cutoffC: 60.5,
    cutoffD: 48.0,
    studentCount: 194,
    meanScore: 61.9,
    stdDev: 20.4,
    sourceType: 'CURRENT_ARCHIVE',
    notes: '2025학년도 2학기 최종 분할점수 (함수/수열 단원 킬러 문항 출제)',
    createdBy: '김수학 교사',
    createdAt: '2025-12-28T11:30:00.000Z',
  },
  {
    id: 'past_2025_1_korean',
    schoolYear: 2025,
    semester: 1,
    grade: 1,
    subjectName: '공통국어',
    midtermWeight: 30,
    performanceWeight: 40,
    finalWeight: 30,
    cutoffA: 89.4,
    cutoffB: 78.2,
    cutoffC: 66.0,
    cutoffD: 53.5,
    studentCount: 195,
    meanScore: 68.8,
    stdDev: 16.5,
    sourceType: 'MANUAL',
    notes: '수행평가 배점 비중 높고 문학 서술형 평가 반영',
    createdBy: '성적관리부 관리자',
    createdAt: '2025-07-22T14:15:00.000Z',
  },
  {
    id: 'past_2024_1_math1',
    schoolYear: 2024,
    semester: 1,
    grade: 1,
    subjectName: '수학 I',
    midtermWeight: 30,
    performanceWeight: 30,
    finalWeight: 40,
    cutoffA: 88.5,
    cutoffB: 76.0,
    cutoffC: 63.2,
    cutoffD: 51.0,
    studentCount: 188,
    meanScore: 65.1,
    stdDev: 18.2,
    sourceType: 'MANUAL',
    notes: '2024학년도 1학기 나이스 등록 분할점수 원본',
    createdBy: '성적관리부 관리자',
    createdAt: '2024-07-19T09:00:00.000Z',
  },
  {
    id: 'past_2024_2_math1',
    schoolYear: 2024,
    semester: 2,
    grade: 1,
    subjectName: '수학 I',
    midtermWeight: 30,
    performanceWeight: 30,
    finalWeight: 40,
    cutoffA: 85.3,
    cutoffB: 72.5,
    cutoffC: 59.8,
    cutoffD: 47.2,
    studentCount: 188,
    meanScore: 60.8,
    stdDev: 21.0,
    sourceType: 'MANUAL',
    notes: '2024학년도 2학기 분할점수 (기말고사 난이도 상향 조정)',
    createdBy: '성적관리부 관리자',
    createdAt: '2024-12-24T16:00:00.000Z',
  },
  {
    id: 'past_2024_1_english',
    schoolYear: 2024,
    semester: 1,
    grade: 1,
    subjectName: '영어 I',
    midtermWeight: 35,
    performanceWeight: 30,
    finalWeight: 35,
    cutoffA: 90.1,
    cutoffB: 79.5,
    cutoffC: 67.2,
    cutoffD: 54.0,
    studentCount: 188,
    meanScore: 70.2,
    stdDev: 17.1,
    sourceType: 'MANUAL',
    notes: '2024학년도 1학기 영어 분할점수',
    createdBy: '성적관리부 관리자',
    createdAt: '2024-07-21T11:00:00.000Z',
  },
  {
    id: 'past_2023_1_math1',
    schoolYear: 2023,
    semester: 1,
    grade: 1,
    subjectName: '수학 I',
    midtermWeight: 30,
    performanceWeight: 30,
    finalWeight: 40,
    cutoffA: 87.8,
    cutoffB: 75.2,
    cutoffC: 62.4,
    cutoffD: 50.1,
    studentCount: 192,
    meanScore: 64.0,
    stdDev: 19.1,
    sourceType: 'MANUAL',
    notes: '2023학년도 1학기 고1 수학 분할점수',
    createdBy: '성적관리부 관리자',
    createdAt: '2023-07-20T10:00:00.000Z',
  },
];

export const initialMappingPresets: ExcelColumnMapping[] = [
  {
    presetName: 'NICE 표준 성적 양식 (2026)',
    studentNameCol: '성명',
    studentNumberCol: '학번',
    gradeCol: '학년',
    classCol: '반',
    numberCol: '번호',
    subjectNameCol: '과목명',
    midtermScoreCol: '중간고사',
    performanceScoreCol: '수행평가',
    finalExpectedScoreCol: '2차고사예상',
  },
  {
    presetName: '교사 교무 수첩 엑셀 양식',
    studentNameCol: '이름',
    studentNumberCol: '번호',
    midtermScoreCol: '1차고사',
    performanceScoreCol: '수행',
    finalExpectedScoreCol: '2차예상',
  },
];
